#
language: python
python: "3.6"
dist: xenial

sudo:  required
services:
    - docker

install:
  - sudo pip install pipenv

before_script:
  - pipenv install
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

script:
  - pipenv run python3 test.py

