language: python
python: '3.6'
dist: xenial
sudo: required
services:
- docker
cache:
  directories:
    - cache_directory
jobs:
  include:
  - stage: "stage1"
    name: "job1"
    script:
      - "ls cache_directory"
      - "touch cache_directory/touch_stage_1_job_1"
  - stage: "stage1"
    name: "job2"
    script:
      - "ls cache_directory"
      - "touch cache_directory/touch_stage_1_job_2"
  - stage: "stage2"
    name: "job1"
    script:
      - "ls cache_directory"
      - "touch cache_directory/touch_stage_2_job_1"
  - stage: "stage2"
    name: "job2"
    script:
      - "ls cache_directory"
      - "touch cache_directory/touch_stage_2_job_2"
stages:
  - "stage1"
  - "stage2"